name: Publish on NPM
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn prettier-check
      - run: yarn test
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
